Localization of VIVO into Serbian (Latin script)
vivo-project/Vitro-languages pull request #55
Opened 2021-11-02 00:58 UTC by VeljkoMaksimovic

This localization is dependent on changes made to Vitro in this pull request vivo-project/Vitro#250

2021-11-29 09:17 UTC, chenejac requested changes
@VeljkoMaksimovic thanks for this contribution. Can you please resolve my comments attached to files? Also, please remove your Serbian comments or translate that in English. At the end, I have one additional question. Why custom ftl files do not have script (alphabet - Latn) in its name? Can that be a problem in the case some VIVO instance has both Serbian Cyrillic and Serbian Latin Translation?

2021-11-29 09:17 UTC, chenejac commented on sr_Latn_RS/pom.xml
> +    <developers>
I suggest to remove completely developers tag. It contains obsolete information about three VIVO contributors not active anymore.

2021-11-29 09:17 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +# TODO Nisam pronasao gde se koriste ove fraze, kad pornađen gde se koriste prevescu ih
Remove comment

2021-11-29 09:17 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +verify_this_match = verify this match
proverite podudaranje

2021-11-29 09:17 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +verify_this_match_title = verify this match
proverite podudaranje

2021-11-29 09:17 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +# TODO Ovo cu prevesti kada shvatim sta zapravo ovo predstavlja
remove comment

2021-11-29 09:17 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +auth_matching_id_label = External Auth. ID / Matching ID
Spoljni ID / Podurajući ID

2021-11-29 09:17 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +auth_id_label = External Authentication ID
ID spoljne/eksterne autentifikacije

2021-11-29 09:17 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +error_external_auth_already_exists = Nalog sa unetim Eksternim Autorizacionim ID-em već postoji.
Nalog sa unetim ID-em Eksterne Autentifikacije već postoji

2021-11-29 09:17 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +# TODO grants=stipendije?
remove comment
grants=grantovi

2021-11-29 09:17 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +manage_grants_and_projects_link = upravljanje stipendijama i projektima
upravljanje grantovima i projektima

2021-11-29 09:17 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +# TODO properties=svojstva??
Please remote the comment. Yes, properties can be translated to "svojstva"

2021-11-29 09:17 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +scroll_to_menus = scroll to property group menus
idite na grupu menija za svojstva

2021-11-29 09:17 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +# TODO Individual sam preveo ovako pošto pojedinac zvuci lose
Individual should be translated as osoba. Please remove the comment.

2021-11-29 09:17 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +entity_to_query_for = Ovaj id je id entiteta za pretragu. Možete koristiti i netid.
The second sentence might be Možete koristiti i identifikator netid. Please remove previous two lines under comments.

2021-11-29 09:17 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +may_edit = Može ažurirati
I would translate this and next property as:
Dozvoljeno ažuriranje
Nije dozvoljeno ažuriranje

2021-11-29 09:17 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +identifier_factories = Fabrike identifikatora
Maybe Centri za identifikatore, depends on context

2021-11-29 09:17 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +# TODO Search Idex = Indeks Pretrage?
Yes, correct. Please remove the comment

2021-11-29 09:17 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +check_startup_status = Proverite stranicu 'status pokretanja' i/ili Tomcat logove za više informacija.
Tomcat logove => logove veb servera

2021-11-29 09:17 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +#current_task = {0} the search index
correct.

2021-11-29 09:17 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +fatal_error = Fatal Error
I think it is better to translate to Fatalna Greška

2021-11-29 09:17 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +viewing_page = Verovatno pregleda stranicu
Verovatno pregledana stranica

2021-11-29 09:17 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +display_admin_header = Display Admin and Configuration
Administracija i Konfiguracija Prikaza

2021-11-29 09:17 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +#TODO Informacije o grešci?
Correct, please translate that as Informacije o grešci

2021-11-29 09:17 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +error_occurred = Došlo je do greške na VIVO sajt
remove VIVO, and replace the last word with sajtu

2021-11-29 09:17 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +trace_available = detaljne informacije o greškama možete naći u vivo log-u
remove vivo

2021-11-29 09:17 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +error_occurred_at = Došlo je do greške na Vašem VIVO sajtu na {0}.
remove VIVO

2021-11-29 09:17 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +fake_external_auth = Falsifikovana Eksterna Autentifikacija
Simulacija Eksterne Autentifikacije

2021-11-29 09:17 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +continued = cont'd
nastaviće se

2021-11-29 09:17 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +#you_can = You can
correct, please remove the comment

2021-11-29 09:17 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +pages = stranice
correct, please remove the comment

2021-11-29 09:17 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +page_curator_permission_option = Curators and above can view this page
Ovu stranicu mogu da vide korisnici sa ulogom koja nije niža od kuratora

2021-11-29 09:17 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +page_editor_permission_option = Urednici i iznad mogu da pristupe ovoj stranici
Ovu stranicu mogu da vide korisnici sa ulogom koja nije niža od urednika

2021-11-29 09:17 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +#TODO Recompute translated as "Rekompajlirate"
correct

2021-11-29 09:17 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +#TODO Not sure how to translate technical term "build date"
Datum izrade is fine.

2021-11-29 09:17 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +#TODO Not sure
correct

2021-11-29 09:17 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +undo_camelcasing = Uncamelcasing
Ukloniti CamelCase notaciju

2021-11-29 09:17 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +#TODO Why are VIVO literals in Vitro-languages
Good point. I think you should remove the word VIVO from the below translations

2021-11-29 09:17 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +page_uri_missing_msg = iGenerisanje stranice nije uspelo jer nije jasno koju stranicu tražite. \
A typo - iGenerisanje => Generisanje

2021-11-29 09:17 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +ingest_tools = Alati za prikupljanje podataka
This is fine

2021-11-29 09:17 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +dump_restore = Ugasite/Obnovite apliakciju
Resetuje/Vratite aplikaciju

2021-11-29 09:17 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +asserted_class_hierarchy = Asserted Class Hierarchy
Hijerarhija utvrđenih klasa

2021-11-29 09:17 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +inferred_class_hierarchy = Inferred Class Hierarchy
Hijerarhija pretpostavljenih klasa

2021-11-29 09:17 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +browse_capitalized = Pretražite
Pregledajte

2021-11-29 09:17 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +browse_by = Pretražite po
Pregledajte po

2021-11-29 09:17 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +select_vclass_uri = Odaberite VKlasu
Odaberite VClass

2021-11-29 09:17 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +#TODO not sure
correct

2021-11-29 09:17 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +#TODO not sure
correct

2021-11-29 09:17 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +#TODO Dont know what cvlassAlpha is
just keep vclassAlpha as is, without translation

2021-11-29 09:17 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +#TODO Not sure how to translate "range class"
klasa raspona ili klasa opsega? or maybe to keep English term range. Choose one option, and it is important that it is consistent across all properties

2021-11-29 09:17 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +with_vitro = Sa Vitro-om moežete:
a typo - moežete -> možete

2021-11-29 09:17 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +sunday = nedelj
a typo - nedelj -> nedelja

2021-11-29 09:17 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +tuesday = utokar
utokar -> utorak

2021-11-29 09:17 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +thursday = cetvrtak
cetvrtak -> četvrtak

2021-11-29 09:17 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +error_processing_labels = Greška priliko obrade zahteva: the unchecked labels could not be deleted.
Greška prilikom obrade zahteva: neoznačene labele se ne mogu obrisati.

2021-11-29 09:17 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +#of_the_results = of the results
correct

2021-11-29 09:17 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +#TODO What is Faux?
I suggest to keep that term Faux. The other option might be to translate as nominalno

2021-11-29 09:17 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +or = ili
duplicated property, see the line 17th of this file

2021-11-29 09:17 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/templates/freemarker/userAccounts-acctCreatedEmail_sr_RS.ftl
> +Česttitamo!
A typo - Čestitamo!

2021-11-29 09:17 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/templates/freemarker/userAccounts-acctCreatedEmail_sr_RS.ftl
> +Nalepite link koji se nalazi ispred u navigacioni bar Vašeg pretraživača kako bi ste
bi ste -> biste

2021-11-29 09:17 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/templates/freemarker/userAccounts-confirmEmailChangedEmail_sr_RS.ftl
> +<#assign subject = "Your ${siteName} email account has been changed." />
not translated

2021-11-29 09:17 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/templates/freemarker/userAccounts-passwordResetCompleteEmail_sr_RS.ftl
> +<#assign subject = "Your ${siteName} password changed." />
not translated!

2021-11-29 09:17 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +select_an_existing = Odaberite postojeći
Duplicated property, see the line 9, remove one instance of this property

2021-11-29 09:17 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/templates/freemarker/search-help_sr_RS.ftl
> +    <h2>Search Tips</h2>
Not translated

2021-11-29 09:17 UTC, chenejac commented on sr_Latn_RS/webapp/src/main/webapp/templates/freemarker/userAccounts-passwordResetPendingEmail_sr_RS.ftl
> +<#assign subject = "${siteName} reset password request" />
not translated

2022-04-06 07:35 UTC, chenejac approved these changes

2022-04-06 13:44 UTC, lidijaivanovic requested changes
Well done. I have added some comments which I hope might improve translation. Also, I notice that each word first capital letter is not so common in Serbian language in titles, therefore I suggest to replace that with sentence style, i.e. capitalize only first letter of the first word.

2022-04-06 13:44 UTC, lidijaivanovic commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +request_failed = Zahtev nije uspeo. Molimo Vas kontaktirajte vašeg administratora.
vašeg => Vašeg

2022-04-06 13:44 UTC, lidijaivanovic commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +cropping_caption = Your profile photo will look like the image below.
nije prevedno

2022-04-06 13:44 UTC, lidijaivanovic commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +confirm_delete = Are you sure you want to delete this photo?
nije prevedeno

2022-04-06 13:44 UTC, lidijaivanovic commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +alt_preview_crop = Preview of photo cropped
nije prevedeno

2022-04-06 13:44 UTC, lidijaivanovic commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +imageUpload.errorNoImageForCropping = There is no image file to be cropped.
nije prevedno

2022-04-06 13:44 UTC, lidijaivanovic commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +external_auth_only = Autentifikacije isključivo puta eksternih servisa
puta - putem

2022-04-06 13:44 UTC, lidijaivanovic commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +reset_password_note = Napomena: Uputstva za resetovanje lozinkee će biti \
lozinke

2022-04-06 13:44 UTC, lidijaivanovic commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +enter_new_password = Molimo Vas unesite novu lozinkuu za korisnika {0}
lozinku

2022-04-06 13:44 UTC, lidijaivanovic commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +password_saved_please_login	= Vaša lozinka je sačuvana. Please log in.
tab pre =

2022-04-06 13:44 UTC, lidijaivanovic commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +#email_changed_subject = "Your VIVO email account has been changed.");
da li ovo treba da bude pod komentarom?

2022-04-06 13:44 UTC, lidijaivanovic commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +background_threads = Pozadinske Niti
niti malim slovom verovatno u duhu našeg jezika

2022-04-06 13:44 UTC, lidijaivanovic commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +dump_restore = Resetujte/Vratite apliakciju
aplikaciju. Da nije vraćanje stanja aplikacije, tj. podataka?

2022-04-06 13:44 UTC, lidijaivanovic commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +controls = Controls
Kontrole ili opcije

2022-04-06 13:44 UTC, lidijaivanovic commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +sparql_query_results = Rezultati Sparql upita
SPARQL

2022-04-06 13:44 UTC, lidijaivanovic commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +menu_item =
stavka menija

2022-04-06 13:44 UTC, lidijaivanovic commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +search_vitro = Pretražite VITRO
Vitro

2022-04-06 14:14 UTC, VeljkoMaksimovic commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +#email_changed_subject = "Your VIVO email account has been changed.");
Vidim da je i u drugim jezicima takođe zakomentarisano. Verovatno zato što se već ranije u fajlu pojavljuje property sa istim nazivom

2022-04-06 14:30 UTC, VeljkoMaksimovic commented on sr_Latn_RS/webapp/src/main/webapp/i18n/all_sr_Latn_RS.properties
> +dump_restore = Resetujte/Vratite apliakciju
Ostavio sam samo Resetujte aplikaciju, poštomisli da bi bilo predugačko da piše Resetujte/ Vretite u inicijalno stanje aplikaciju

2022-04-06 17:04 UTC, lidijaivanovic approved these changes

2022-04-08 11:24 UTC, litvinovg commented
Should freemarker template filenames also have _sr_Latn_RS suffix instead of _sr_RS ?

2022-04-20 01:36 UTC, VeljkoMaksimovic commented
@litvinovg .ftl templates were working fine with sr_RS, just finished testing them, but you are right, it is better to be more specific with the script. All of those files are now renamed to end with sr_Latn_RS

2022-04-20 07:34 UTC, chenejac approved these changes

2022-04-21 13:16 UTC, merged