[ i18n sprint ] new translations for fixed new individual form
vivo-project/Vitro-languages pull request #59
Opened 2022-10-06 13:41 UTC by litvinovg

Translations for new key used in 
[VIVO PR](https://github.com/vivo-project/VIVO/pull/3776)
[Vitro PR](https://github.com/vivo-project/Vitro/pull/332)

2022-10-07 06:35 UTC, bkampe requested changes
german translation would work, but "Erstellen eines Objekts der Art" is better.

2022-10-07 06:39 UTC, bkampe commented on de_DE/webapp/src/main/webapp/i18n/all_de_DE.properties
> +create_new_individual_of_the_following_type = Erstellen der folgenden Art von Objekt
```suggestion
create_new_individual_of_the_following_type = Erstellen eines Objekts der Art
```

2022-10-21 09:16 UTC, chenejac approved these changes
Ok for Serbian. Please accept suggestion from Benjamin Kampe.

2022-10-25 14:36 UTC, wwelling approved these changes
This is a blocker for PRs in templates using these new i18n properties.

2022-10-27 13:05 UTC, merged