[i18n sprint] moving translations for search help tips from ftl files to property files
vivo-project/Vitro-languages pull request #60
Opened 2022-10-07 10:08 UTC by chenejac

[Companion PR](https://github.com/vivo-project/VIVO/pull/3778)
# What does this pull request do? #
Moves translations from ftl pages to properties.
# How to test # 
Page to test /searchHelp
# Translations review # 
The sixth advanced tip is missing for Germany, at the moment it is in English
Translations for other languages didn't change, just copied from ftl files to property files.

2022-10-07 10:52 UTC, bkampe requested changes

2022-10-07 10:52 UTC, bkampe commented on de_DE/webapp/src/main/webapp/i18n/all_de_DE.properties
> +advanced_search_tip_six = Search uses shortened versions of words -- e.g., a search for <i>cogniti*</i> finds nothing, while <i>cognit*</i> finds both <i>cognitive</i> and <i>cognition</i>.
```suggestion
advanced_search_tip_six = Die Suche verwendet verkürzte Versionen von Wörtern – z. B. findet eine Suche nach <i>cogniti*</i> nichts, während <i>cognit*</i> sowohl <i>cognitive</i> als auch <i>cognition findet </i>.
```

2022-10-07 10:57 UTC, bkampe requested changes

2022-10-07 10:57 UTC, bkampe commented on de_DE/webapp/src/main/webapp/i18n/all_de_DE.properties
> +advanced_search_tip_six = Die Suche verwendet verkürzte Versionen von Wörtern – z. B. findet eine Suche nach <i>cogniti*</i> nichts, während <i>cognit*</i> sowohl <i>cognitive</i> als auch <i>cogniti
```suggestion
advanced_search_tip_six = Die Suche verwendet verkürzte Versionen von Wörtern – z. B. findet eine Suche nach <i>cogniti*</i> nichts, während <i>cognit*</i> sowohl <i>cognitive</i> als auch <i>cognition</i> findet.
```

2022-10-07 11:34 UTC, bkampe requested changes
Minor spelling correction

2022-10-07 11:34 UTC, bkampe commented on de_DE/webapp/src/main/webapp/i18n/all_de_DE.properties
>  error_processing_labels = Fehler bei der Verarbeitung der Anfrage: Die deaktivierten Labels konnte nicht gelöscht werden.
```suggestion
error_processing_labels = Fehler bei der Verarbeitung der Anfrage: Die deaktivierten Labels konnten nicht gelöscht werden.
```

2022-10-21 12:14 UTC, litvinovg commented on ru_RU/webapp/src/main/webapp/i18n/all_ru_RU.properties
> +back_to_results = Back to results
```suggestion
back_to_results = Назад к результатам поиска
```

2022-10-21 12:27 UTC, litvinovg approved these changes
Looks good. Take a look at my suggestion.

2022-11-01 15:36 UTC, bkampe requested changes
Minor spelling correction in german translation

2022-11-01 15:36 UTC, bkampe commented on de_DE/webapp/src/main/webapp/i18n/all_de_DE.properties
> +search_tip_three = Mit Ausnahme Boolescher Operatoren, sind Suchen <strong>nicht</strong> case-sensitive, also sind "Genf" und "genf" identisch.
```suggestion
search_tip_three = Mit Ausnahme boolescher Operatoren, sind Suchen <strong>nicht</strong> case-sensitive, also sind "Genf" und "genf" identisch.
```

2022-11-01 15:36 UTC, bkampe commented on de_DE/webapp/src/main/webapp/i18n/all_de_DE.properties
> +advanced_search_tip_three = Wortgruppensuchen können mit Booleschen Operatoren kombiniert werden - z.B. "<i>Klimaveränderung</i>" OR "<i>Globale Erwärmung</i>".
```suggestion
advanced_search_tip_three = Wortgruppensuchen können mit booleschen Operatoren kombiniert werden - z.B. "<i>Klimaveränderung</i>" OR "<i>Globale Erwärmung</i>".
```

2022-11-01 15:36 UTC, bkampe commented on de_DE/webapp/src/main/webapp/i18n/all_de_DE.properties
> +advanced_search_tip_four = Wortvariationen werden auch gefunden - Bsp.: <i>Sequenz</i> findet <i>Sequenzen</i> and <i>Sequenzierung</i>.
```suggestion
advanced_search_tip_four = Wortvariationen werden auch gefunden - Bsp.: <i>Sequenz</i> findet <i>Sequenzen</i> und <i>Sequenzierung</i>.
```

2022-11-08 10:53 UTC, bkampe approved these changes

2022-11-08 10:59 UTC, merged